/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FeedAuthorIdImport } from './routes/feed/$authorId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FeedAuthorIdRoute = FeedAuthorIdImport.update({
  id: '/feed/$authorId',
  path: '/feed/$authorId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/feed/$authorId': {
      id: '/feed/$authorId'
      path: '/feed/$authorId'
      fullPath: '/feed/$authorId'
      preLoaderRoute: typeof FeedAuthorIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/feed/$authorId': typeof FeedAuthorIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/feed/$authorId': typeof FeedAuthorIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/feed/$authorId': typeof FeedAuthorIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feed/$authorId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed/$authorId'
  id: '__root__' | '/' | '/feed/$authorId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FeedAuthorIdRoute: typeof FeedAuthorIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FeedAuthorIdRoute: FeedAuthorIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/feed/$authorId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/feed/$authorId": {
      "filePath": "feed/$authorId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
