name: Biome

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  frontend:
    name: "Lint Frontend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  backend:
    name: "Lint Backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .